#vectorization & selection in an array

In [3]:
x= list(range(1,11))
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
x*2 #replication

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
import numpy as np 

In [6]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
a+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [9]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
a-2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [11]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
vactorixation with comparison operators 

In [15]:
3>4

False

In [16]:
a>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [17]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

### masking

In [ ]:
packing--> to get the output of true or false value to actual value 

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#what are all those numbers which are greter than 4 

In [20]:
a>4


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
mask=a>4
a[mask]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [26]:
mask=a%2==0
a[mask]

array([ 2,  4,  6,  8, 10])

##vectorisation with comparision operators will give you the boolean value i.e TRue or False 
##Masking will give youthe actual value for which the condition is true 

In [27]:
###selction of array

In [28]:
names=np.array(["jay","raj","jay","kumar","mrityunjay","kumar","jay","rohit","suraj","rvi"])

In [29]:
#select all the names where the value is jay 
names =="jay"

array([ True, False,  True, False, False, False,  True, False, False,
       False])

In [30]:
mask=names=="jay"

In [31]:
names[mask]

array(['jay', 'jay', 'jay'], dtype='<U10')

In [32]:
names[names=="jay"]

array(['jay', 'jay', 'jay'], dtype='<U10')

In [ ]:
#select all the names where the values is not jay 

In [33]:
names[names!="jay"]

array(['raj', 'kumar', 'mrityunjay', 'kumar', 'rohit', 'suraj', 'rvi'],
      dtype='<U10')

In [36]:
import numpy as np 
names

array(['jay', 'raj', 'jay', 'kumar', 'mrityunjay', 'kumar', 'jay',
       'rohit', 'suraj', 'rvi'], dtype='<U10')

In [38]:
#select all the names execept jay and kumar 
cond1=(names!="jay")
cond2=(names!="kumar")
cond1

array([False,  True, False,  True,  True,  True, False,  True,  True,
        True])

In [39]:
cond2

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [40]:
cond1 & cond2

array([False,  True, False, False,  True, False, False,  True,  True,
        True])

In [41]:
names[cond1 & cond2]

array(['raj', 'mrityunjay', 'rohit', 'suraj', 'rvi'], dtype='<U10')

In [42]:
names[(names!="jay")&(names!="kumar")]

array(['raj', 'mrityunjay', 'rohit', 'suraj', 'rvi'], dtype='<U10')

In [44]:
#select all those names where name is not mrityunjay and assign then as shiv 
#step 1 
names!="mrityunjay"

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [45]:
names[names!="mrityunjay"]

array(['jay', 'raj', 'jay', 'kumar', 'kumar', 'jay', 'rohit', 'suraj',
       'rvi'], dtype='<U10')

In [48]:
names[names!="mrityunjay"]= "shiv"
names

array(['shiv', 'shiv', 'shiv', 'shiv', 'mrityunjay', 'shiv', 'shiv',
       'shiv', 'shiv', 'shiv'], dtype='<U10')

In [49]:
np.unique(names)

array(['mrityunjay', 'shiv'], dtype='<U10')